name: Run Unit Test
on:
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        log: [ 'test-v', 'test' ]
    name: "unit test ${{ matrix.log }}"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: go get . && make install
      - name: Generate pom.go
        run: make xgen
      - name: Run Unit Tests
        run: make test
        env:
          - TEST_LOG: ${{ matrix.log }}
